### ISSUE TITLE
Enforce eslint fix through precommit

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/incore-playbook#302]
### Targeting Mar 4 for incorporating eslint fix

See example
```
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: bash -c "npx eslint --fix src"
        language: system
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: bash -c "npx prettier src --write"
        language: system
```

Clowder example:
https://github.com/clowder-framework/clowder2/pull/846
